name: EvoRainbow-Metaworld
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - fastrand==1.8.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - glfw==2.6.5
      - gym==0.12.1
      - gymnasium==0.29.1
      - idna==3.6
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - metaworld==2.0.0
      - mujoco==2.3.7
      - numpy==1.24.4
      - pandas==1.5.3
      - pillow==10.2.0
      - protobuf==4.25.2
      - psutil==5.9.8
      - pyglet==2.0.10
      - pyopengl==3.1.7
      - python-dateutil==2.8.2
      - pytz==2023.4
      - pyyaml==6.0.1
      - requests==2.31.0
      - scipy==1.10.1
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - torch==1.4.0
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - wandb==0.16.2
      - zipp==3.17.0
prefix: /home/ubuntu/anaconda3/envs/Metaworld-v2
